#!/usr/bin/env python
"""
bm3d-streak-removal benchmark using shared test data.

Loads sinogram data generated by the main benchmark and runs bm3d-streak-removal.
Results are saved for integration with the unified comparison.

Usage:
    cd bm3d_streak_test && pixi run run
"""

import time
from pathlib import Path

import numpy as np
from skimage.metrics import peak_signal_noise_ratio, structural_similarity

# bm3d-streak-removal imports
from bm3d_streak_removal import multiscale_streak_removal, extreme_streak_attenuation

# Timing configuration - must match joss_comparison.py for scientific rigor
NUM_TIMING_RUNS = 30

# Paths
STUDY_DIR = Path(__file__).parent.parent
DATA_DIR = STUDY_DIR / "results" / "linux_x86_64" / "data"


def load_test_data():
    """Load test data generated by main benchmark."""
    print("Loading test data from main benchmark...")

    sinogram_clean = np.load(DATA_DIR / "sinogram_clean.npy")
    sinogram_rings = np.load(DATA_DIR / "sinogram_rings.npy")

    print(f"  Sinogram shape: {sinogram_rings.shape}")
    print(f"  Data directory: {DATA_DIR}")

    return sinogram_clean, sinogram_rings


def run_bm3d_streak_removal(sinogram):
    """Apply bm3d-streak-removal.

    Expected input shape for multiscale_streak_removal: (angle, sinogram_idx, detector)
    So single sinogram of shape (N_angles, N_detectors) becomes (N_angles, 1, N_detectors).
    """
    # sinogram is (theta, detector)
    # Expected shape: (angle, sino_idx, detector)
    sino_3d = sinogram.astype(np.float64)[:, np.newaxis, :]
    print(f"  Input shape for bm3d-streak: {sino_3d.shape}")

    # Scale to avoid log(0) issues
    sino_scaled = sino_3d + 0.1
    sino_log = np.log(sino_scaled)
    sino_attenuated = extreme_streak_attenuation(sino_log)

    # Use default parameters for fair comparison
    sino_denoised = multiscale_streak_removal(sino_attenuated)
    result = np.exp(sino_denoised) - 0.1
    return result[:, 0, :]


def compute_metrics(result, ground_truth):
    """Compute PSNR and SSIM."""
    result = np.asarray(result, dtype=np.float64)
    ground_truth = np.asarray(ground_truth, dtype=np.float64)

    result_norm = (result - result.min()) / (result.max() - result.min() + 1e-10)
    gt_norm = (ground_truth - ground_truth.min()) / (
        ground_truth.max() - ground_truth.min() + 1e-10
    )

    psnr = peak_signal_noise_ratio(gt_norm, result_norm, data_range=1.0)
    ssim = structural_similarity(gt_norm, result_norm, data_range=1.0)
    return psnr, ssim


def main():
    print("=" * 60)
    print("bm3d-streak-removal Benchmark")
    print("=" * 60)

    # Check if test data exists
    if not DATA_DIR.exists():
        print(f"\nERROR: Test data not found at {DATA_DIR}")
        print("Please run the main benchmark first:")
        print("  cd .. && pixi run benchmark")
        return {"success": False, "error": "Test data not found"}

    # Load test data
    try:
        ground_truth, sinogram_rings = load_test_data()
    except FileNotFoundError as e:
        print(f"\nERROR: {e}")
        print("Please run the main benchmark first:")
        print("  cd .. && pixi run benchmark")
        return {"success": False, "error": str(e)}

    print(f"\nRunning bm3d-streak-removal ({NUM_TIMING_RUNS} timing runs)...")

    try:
        # Timing runs
        times = []
        result = None
        for i in range(NUM_TIMING_RUNS):
            print(f"  Run {i+1}/{NUM_TIMING_RUNS}...", end=" ", flush=True)
            start = time.perf_counter()
            result = run_bm3d_streak_removal(sinogram_rings)
            elapsed = time.perf_counter() - start
            times.append(elapsed)
            print(f"{elapsed:.3f}s")

        time_mean = np.mean(times)
        time_std = np.std(times)

        psnr, ssim = compute_metrics(result, ground_truth)

        print(f"\n  Time: {time_mean:.3f} ± {time_std:.3f} s")
        print(f"  PSNR: {psnr:.2f} dB")
        print(f"  SSIM: {ssim:.4f}")
        print(f"  Output shape: {result.shape}")

        # Save result for unified visualization
        np.save(DATA_DIR / "result_bm3d-streak-removal.npy", result)
        print(f"\n  Result saved to: {DATA_DIR / 'result_bm3d-streak-removal.npy'}")

        # Save metrics
        import csv
        metrics_file = DATA_DIR / "bm3d_streak_metrics.csv"
        with open(metrics_file, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["method", "time_mean", "time_std", "psnr", "ssim"])
            writer.writerow([
                "bm3d-streak-removal",
                f"{time_mean:.3f}",
                f"{time_std:.3f}",
                f"{psnr:.2f}",
                f"{ssim:.4f}",
            ])
        print(f"  Metrics saved to: {metrics_file}")

        print("\n" + "=" * 60)
        print("BENCHMARK COMPLETE")
        print("=" * 60)
        print("\nNext step: Generate unified visualization:")
        print("  cd .. && pixi run visualize")

        return {"time_mean": time_mean, "time_std": time_std, "psnr": psnr, "ssim": ssim, "success": True}

    except Exception as e:
        elapsed = time.perf_counter() - start
        print(f"  ERROR: {e}")
        import traceback
        traceback.print_exc()
        return {"time": elapsed, "error": str(e), "success": False}


if __name__ == "__main__":
    result = main()
    if not result["success"]:
        print("\n" + "=" * 60)
        print("BENCHMARK FAILED")
        print("=" * 60)
