name: bm3dornl
channels:
  - conda-forge
  - nvidia
dependencies:
  # base
  - python>=3.10
  - pip
  - versioningit
  # compute
  - cupy
  - numba
  - scipy<1.13  # avoid a bug in 1.13
  # [Optional]visualization
  - matplotlib
  # [Optional]jupyter
  - jupyterlab
  # utils
  - pre-commit
  - line_profiler  # useful for development
  - memory_profiler  # useful for development
  # packaging
  - anaconda-client
  - boa
  - conda-build < 4
  - conda-verify
  - libmamba
  - libarchive
  - python-build
  # test
  - pytest
  - pytest-cov
  - pytest-xdist
  # pip packages
  - pip:
    - bm3d-streak-removal  # this is our reference package
